
package presentacion;

import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import negocio.Articulo;
import negocio.Comercio;
import negocio.Compra;
import negocio.Item;

public class VentanaConsultarCompra extends javax.swing.JFrame {
    private VentanaPrincipal ventPrin;
    private Comercio comercio;
    private DefaultTableModel modelo;

    public VentanaConsultarCompra(VentanaPrincipal vp, Comercio c){
        initComponents();
        modelo=(DefaultTableModel)tabla.getModel();
        tabla.setModel(modelo);
        ventPrin=vp;
        comercio=c;
        for(Compra iter:comercio.getListadoCompras())
            cmbListaCompras.addItem(iter);
        cmbListaCompras.setSelectedIndex(-1);
        disableAllComponentsButVolverYSel();
    }
    
    public void disableAllComponentsButVolverYSel(){
        Component[] componentes=this.getContentPane().getComponents();
        for(Component iter:componentes)
            iter.setEnabled(false);
        tabla.setEnabled(false);
        btnVolver.setEnabled(true);
        cmbListaCompras.setEnabled(true);
    }
    
    public void enableAllComponents(){
        Component[] componentes=this.getContentPane().getComponents();
        for(Component iter:componentes)
            iter.setEnabled(true);
        tabla.setEnabled(true);
    }
    
    public void limpiarPantalla(){
        txtCodigoCompra.setText("");
        txtMontoTotal.setText("");
        int cantFilas=modelo.getRowCount();
        for(int i=0;i<cantFilas;i++)
            modelo.removeRow(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetalleDeArticulosComprados = new javax.swing.JLabel();
        lblSeleccione = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMontoTotal = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        cmbListaCompras = new javax.swing.JComboBox<>();
        lblCodigoCompra = new javax.swing.JLabel();
        txtCodigoCompra = new javax.swing.JTextField();
        jScrollTabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consultar Compra");

        lblDetalleDeArticulosComprados.setText("Detalle de articulos comprados: ");

        lblSeleccione.setText("Seleccione la Compra a consultar: ");

        lblMontoTotal.setText("Monto Total:");

        txtMontoTotal.setEditable(false);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cmbListaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaComprasActionPerformed(evt);
            }
        });

        lblCodigoCompra.setText("Codigo de Compra: ");

        txtCodigoCompra.setEditable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANT.", "Cod.", "DESCRIPCION", "Costo U.", "% Gan.", "Origen", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollTabla.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeleccione)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbListaCompras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblMontoTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollTabla, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblCodigoCompra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoCompra))
                                    .addComponent(lblDetalleDeArticulosComprados))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccione)
                    .addComponent(cmbListaCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoCompra)
                    .addComponent(txtCodigoCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetalleDeArticulosComprados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoTotal))
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventPrin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cmbListaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaComprasActionPerformed
        if(cmbListaCompras.getSelectedIndex()==-1){
            disableAllComponentsButVolverYSel();
            limpiarPantalla();
        }
        else{
            limpiarPantalla();
            enableAllComponents();
            Compra compra=(Compra)cmbListaCompras.getSelectedItem();
            for(Item iter:compra.getDetalleCompra()){
                Articulo art=iter.getArt();
                Object[] fila={iter.getCant(),art.getCodigo(),art.getDescripcion(),art.getCostoUnitario(),art.getPorcGanancia(),art.descripcionImportado(),iter.valorCompraItem()};
                modelo.addRow(fila);
            }
            txtCodigoCompra.setText(String.valueOf(compra.getCodigo()));
            txtMontoTotal.setText(String.valueOf(compra.montoTotalCompra()));
        }
    }//GEN-LAST:event_cmbListaComprasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Compra> cmbListaCompras;
    private javax.swing.JScrollPane jScrollTabla;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigoCompra;
    private javax.swing.JLabel lblDetalleDeArticulosComprados;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblSeleccione;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCodigoCompra;
    private javax.swing.JTextField txtMontoTotal;
    // End of variables declaration//GEN-END:variables
}
