
package presentacion;

import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import negocio.Articulo;
import negocio.Comercio;
import negocio.Item;
import negocio.PedidoEnConstruccion;
import negocio.PresupuestoEnConstruccion;

public class VentanaNuevoItem extends javax.swing.JFrame {
    private VentanaNuevaCompra ventNueCompra;
    private VentanaNuevaVenta ventNueVenta;
    private PedidoEnConstruccion pedido;
    private PresupuestoEnConstruccion presupuesto;
    private Comercio comercio;  
    private int ventanaSolicitante;//Asigaremos 1 para cuando llame Nueva Compra y 2 para cuando llame Nueva Venta

    public VentanaNuevoItem(VentanaNuevaCompra vnc, PedidoEnConstruccion ped, Comercio c) {
        initComponents();
        ventanaSolicitante=1;
        ventNueCompra=vnc;
        pedido=ped;
        comercio=c;
        for(Articulo iter:comercio.getListaArticulos())
            cmbListaArticulos.addItem(iter);
        cmbListaArticulos.setSelectedIndex(-1);
        disableAllComponentsButVolverAndSelect();
    }
    
    public VentanaNuevoItem(VentanaNuevaVenta vnv, PresupuestoEnConstruccion pres, Comercio c) {
        initComponents();
        ventanaSolicitante=2;
        ventNueVenta=vnv;
        presupuesto=pres;
        comercio=c;
        for(Articulo iter:comercio.getListaArticulos())
            cmbListaArticulos.addItem(iter);
        cmbListaArticulos.setSelectedIndex(-1);
        disableAllComponentsButVolverAndSelect();
    }
    
    private void soloNumerosEnteros(KeyEvent e,JTextField comp){
        char c=e.getKeyChar();
        if(!Character.isDigit(c)&&c!=KeyEvent.VK_BACK_SPACE){
            e.consume();
            getToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico mayor a cero");
        }       
    }
    
    public void enableAllComponents(){
        Component[] componentes=this.getContentPane().getComponents();
        for(Component iter:componentes)
            iter.setEnabled(true);
    }
    
    public void disableAllComponentsButVolverAndSelect(){
        Component[] componentes=this.getContentPane().getComponents();
        for(Component iter:componentes)
            iter.setEnabled(false);
        btnVolver.setEnabled(true);
        cmbListaArticulos.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccioneArticulo = new javax.swing.JLabel();
        cmbListaArticulos = new javax.swing.JComboBox<>();
        lblCantidadDelArticulo = new javax.swing.JLabel();
        txtCantidadDelArticulo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nuevo Item a Comprar");

        lblSeleccioneArticulo.setText("Seleccione Articulo: ");

        cmbListaArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaArticulosActionPerformed(evt);
            }
        });

        lblCantidadDelArticulo.setText("Cantidad:");

        txtCantidadDelArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadDelArticuloKeyTyped(evt);
            }
        });

        btnAgregar.setText("Agregar ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidadDelArticulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidadDelArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeleccioneArticulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbListaArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccioneArticulo)
                    .addComponent(cmbListaArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDelArticulo)
                    .addComponent(txtCantidadDelArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnVolver))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if(ventanaSolicitante==1){
            ventNueCompra.setVisible(true);
            dispose();
        }
        if(ventanaSolicitante==2){
            ventNueVenta.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtCantidadDelArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadDelArticuloKeyTyped
        soloNumerosEnteros(evt, txtCantidadDelArticulo);
    }//GEN-LAST:event_txtCantidadDelArticuloKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        boolean error=false;
        int can=0;
        String cant=txtCantidadDelArticulo.getText().trim();
        if(cant.isEmpty())
            error=true;
        else
        can=Integer.parseInt(cant);
        
        if(!error){
            Item i=new Item((Articulo)cmbListaArticulos.getSelectedItem(), can);
            if(ventanaSolicitante==1){
                ventNueCompra.addItem(i);
                ventNueCompra.actualizarListadoItems();
                ventNueCompra.actualizarMontoTotal();
                ventNueCompra.setVisible(true);
                dispose();
            }
            if(ventanaSolicitante==2){
                if(!ventNueVenta.addItem(i))
                    javax.swing.JOptionPane.showMessageDialog(null, "La cantidad a vender es superior al stock");
                else{
                ventNueVenta.actualizarListadoItems();
                ventNueVenta.actualizarMontoTotal();
                ventNueVenta.setVisible(true);
                dispose();
                }
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbListaArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaArticulosActionPerformed
        enableAllComponents();
    }//GEN-LAST:event_cmbListaArticulosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Articulo> cmbListaArticulos;
    private javax.swing.JLabel lblCantidadDelArticulo;
    private javax.swing.JLabel lblSeleccioneArticulo;
    private javax.swing.JTextField txtCantidadDelArticulo;
    // End of variables declaration//GEN-END:variables
}
