
package presentacion;

import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import negocio.Articulo;
import negocio.Comercio;
import negocio.Item;
import negocio.PresupuestoEnConstruccion;
import negocio.Venta;

public class VentanaNuevaVenta extends javax.swing.JFrame {
    private VentanaPrincipal ventPrinc;
    private Comercio comercio;
    private PresupuestoEnConstruccion presupuesto;
    private DefaultTableModel modeloPresupuesto;

    public VentanaNuevaVenta(VentanaPrincipal vp, Comercio c) {
        initComponents();
        ventPrinc=vp;
        comercio=c;
        presupuesto=new PresupuestoEnConstruccion();
        modeloPresupuesto=(DefaultTableModel)tablaPresupuesto.getModel(); 
        
    }
    
    public boolean addItem(Item i){
        return presupuesto.addItem(i);
    }
    
    public void limpiarTabla(){
        int cantFilas=modeloPresupuesto.getRowCount();
        for(int i=0;i<cantFilas;i++)
            modeloPresupuesto.removeRow(0);
    }
    
    public void actualizarListadoItems(){
        limpiarTabla();
        for(Item iter:presupuesto.getDetallePresupuesto()){
            Articulo art=iter.getArt();
            Object[] datosFila={iter.getCodigo(),iter.getCant(),art.getCodigo(),art.getDescripcion(),art.descripcionImportado(),art.precioFinal(),iter.valorVentaItem()};
            modeloPresupuesto.addRow(datosFila);
        }
    }
    
    public void actualizarMontoTotal(){
        txtMontoTotal.setText(String.valueOf(presupuesto.montoTotalVenta()));
    }
    
    private void formatoDni(KeyEvent e,JTextField comp){
        char c=e.getKeyChar();
        if(!Character.isDigit(c)&&c!=KeyEvent.VK_BACK_SPACE||comp.getText().trim().length()>=8){
            e.consume();
            getToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(null, "El DNI debe tener 8 digitos y no puede contener puntos");
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetalleDeArticulos = new javax.swing.JLabel();
        lblNuevaVenta = new javax.swing.JLabel();
        btnAgregarItemALaVenta = new javax.swing.JButton();
        lblMontoTotal = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        btnConfirmarVenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblDniComprador = new javax.swing.JLabel();
        txtDniComprador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresupuesto = new javax.swing.JTable();
        btnEliminarItems = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nueva Venta");

        lblDetalleDeArticulos.setText("Detalle de articulos:");

        lblNuevaVenta.setText("Nueva Venta en carga:");

        btnAgregarItemALaVenta.setText("Agregar Item a la Venta");
        btnAgregarItemALaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarItemALaVentaActionPerformed(evt);
            }
        });

        lblMontoTotal.setText("Monto Total:");

        txtMontoTotal.setEditable(false);

        btnConfirmarVenta.setText("Confirmar Venta");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblDniComprador.setText("D.N.I. del comprador: ");

        txtDniComprador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniCompradorKeyTyped(evt);
            }
        });

        tablaPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Nº", "Cant.", "Cod.Art.", "Descripcion", "Importado", "Precio Unit.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPresupuesto);

        btnEliminarItems.setText("Eliminar Items");
        btnEliminarItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDniComprador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniComprador))
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblMontoTotal)
                                .addGap(22, 22, 22)
                                .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDetalleDeArticulos)
                                    .addComponent(lblNuevaVenta))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarItemALaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarItems, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevaVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniComprador)
                    .addComponent(txtDniComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblDetalleDeArticulos)
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoTotal)
                    .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarItemALaVenta)
                    .addComponent(btnEliminarItems))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarVenta)
                    .addComponent(btnVolver))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGap(121, 121, 121)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventPrinc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarItemALaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarItemALaVentaActionPerformed
        VentanaNuevoItem vni= new VentanaNuevoItem(this, presupuesto, comercio);
        vni.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarItemALaVentaActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        boolean error=false;
        String dni=txtDniComprador.getText().trim();
        if(dni.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor ingrese el DNI del cliente");
            error=true;
        }
        if(presupuesto.getDetallePresupuesto().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Agregue primero los items a comprar");
            error=true;
        }
        
        if(!error){
            LinkedList<Item> copiaDetPres=new LinkedList(presupuesto.getDetallePresupuesto());
            Venta v=new Venta(dni,copiaDetPres);
            comercio.addVenta(v);
            limpiarTabla();
            presupuesto.getDetallePresupuesto().clear();
            txtMontoTotal.setText("");
            txtDniComprador.setText("");
            javax.swing.JOptionPane.showMessageDialog(null, "La venta se registro correctamente");
        }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void txtDniCompradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniCompradorKeyTyped
        formatoDni(evt,txtDniComprador);
    }//GEN-LAST:event_txtDniCompradorKeyTyped

    private void btnEliminarItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarItemsActionPerformed
        int[] filasSeleccionadas=tablaPresupuesto.getSelectedRows();
        if(filasSeleccionadas.length==0)
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione items a eliminar");
        else{
        int cantFilasAEliminar=filasSeleccionadas.length;
        for(int i=0;i<cantFilasAEliminar;i++){
            int fila=filasSeleccionadas[i];
            int codItem=(int)modeloPresupuesto.getValueAt(fila,0);
            presupuesto.removeItem(codItem);
        }
        actualizarListadoItems();
        actualizarMontoTotal();
        }
    }//GEN-LAST:event_btnEliminarItemsActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarItemALaVenta;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnEliminarItems;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDetalleDeArticulos;
    private javax.swing.JLabel lblDniComprador;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblNuevaVenta;
    private javax.swing.JTable tablaPresupuesto;
    private javax.swing.JTextField txtDniComprador;
    private javax.swing.JTextField txtMontoTotal;
    // End of variables declaration//GEN-END:variables
}
