
package presentacion;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JTextField;
import negocio.Articulo;
import negocio.Comercio;

public class VentanaModificarArticulo extends javax.swing.JFrame {

    public VentanaModificarArticulo(VentanaPrincipal vp, Comercio c) {
        initComponents();
        ventPrincipal=vp;
        comercio=c;
        listArt=comercio.getListaArticulos();
        for(Articulo iter:listArt)
            cmbListaArticulos.addItem(iter);
        cmbListaArticulos.setSelectedIndex(-1);
    }
    
    public void limpiarPantalla(){
        lblShowCodigo.setText("");
        lblShowStockActual.setText("");
        txtDescripcion.setText("");
        txtCosto.setText("");
        txtPorcGanancia.setText("");
        btnGroupImportado.clearSelection();
        cmbListaArticulos.setSelectedIndex(-1);
        disableAllComponentsButSelectAndVolver();
    }
    
    private void soloNumeros(KeyEvent e,JTextField comp){
        char c=e.getKeyChar();
        if(!Character.isDigit(c)&&c!=KeyEvent.VK_BACK_SPACE&&c!='.'||(c=='.'&&comp.getText().trim().contains("."))){
            e.consume();
            getToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico mayor a cero");
        }       
    }
    
    public void disableAllComponentsButSelectAndVolver(){
        Component[] componentes=this.getContentPane().getComponents();
        for(Component iter:componentes)
            iter.setEnabled(false);
        btnVolver.setEnabled(true);
        cmbListaArticulos.setEnabled(true);
    }
    
    public void enableAllComponents(){
        Component[] componentes=this.getContentPane().getComponents();
        for(Component iter:componentes)
            iter.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupImportado = new javax.swing.ButtonGroup();
        cmbListaArticulos = new javax.swing.JComboBox<>();
        lblSeleccionarArticulo = new javax.swing.JLabel();
        lblDatosDelArticulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblShowCodigo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblStockActual = new javax.swing.JLabel();
        lblShowStockActual = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblPorcGanancia = new javax.swing.JLabel();
        txtPorcGanancia = new javax.swing.JTextField();
        lblImportado = new javax.swing.JLabel();
        opcImpSi = new javax.swing.JRadioButton();
        opcImpNo = new javax.swing.JRadioButton();
        btnConfirmarCambios = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        EliminarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modificar Articulo");

        cmbListaArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaArticulosActionPerformed(evt);
            }
        });

        lblSeleccionarArticulo.setText("Seleccione el articulo a modificar:");

        lblDatosDelArticulo.setText("Datos del articulo:");

        lblCodigo.setText("Codigo:");

        lblDescripcion.setText("Descripcion: ");

        lblStockActual.setText("Stock actual:");

        lblCosto.setText("Costo: ");

        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
        });

        lblPorcGanancia.setText("Porcentaje de ganancia (%): ");

        txtPorcGanancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcGananciaKeyTyped(evt);
            }
        });

        lblImportado.setText("Importado: ");

        btnGroupImportado.add(opcImpSi);
        opcImpSi.setText("Si");

        btnGroupImportado.add(opcImpNo);
        opcImpNo.setText("No");

        btnConfirmarCambios.setText("Confirmar cambios");
        btnConfirmarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCambiosActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        EliminarArticulo.setText("Eliminar articulo");
        EliminarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSeleccionarArticulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbListaArticulos, 0, 221, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescripcion)
                                .addGap(0, 0, 0)
                                .addComponent(txtDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCosto)
                                .addGap(0, 0, 0)
                                .addComponent(txtCosto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPorcGanancia)
                                .addGap(0, 0, 0)
                                .addComponent(txtPorcGanancia))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatosDelArticulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblShowCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStockActual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblShowStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblImportado)
                                        .addGap(18, 18, 18)
                                        .addComponent(opcImpSi)
                                        .addGap(18, 18, 18)
                                        .addComponent(opcImpNo)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnConfirmarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EliminarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionarArticulo)
                    .addComponent(cmbListaArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatosDelArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblShowCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStockActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblShowStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcGanancia)
                    .addComponent(txtPorcGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImportado)
                    .addComponent(opcImpSi)
                    .addComponent(opcImpNo))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarCambios)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EliminarArticulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbListaArticulos.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListaArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaArticulosActionPerformed
        Articulo art=(Articulo)cmbListaArticulos.getSelectedItem();
        if(art!=null){
            enableAllComponents();
            lblShowCodigo.setText(String.valueOf(art.getCodigo()));
            lblShowStockActual.setText(String.valueOf(art.getStock()));
            txtDescripcion.setText(art.getDescripcion());
            txtCosto.setText(String.valueOf(art.getCostoUnitario()));
            txtPorcGanancia.setText(String.valueOf(art.getPorcGanancia()));
            if(art.isImportado())
                opcImpSi.setSelected(true);
            else
                opcImpNo.setSelected(true);
        }
        else{
            limpiarPantalla();
        }
    }//GEN-LAST:event_cmbListaArticulosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        ventPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCambiosActionPerformed
        boolean errorD=false, errorCos=false, errorPor=false, errorI=false;
        String desc=txtDescripcion.getText().trim().toUpperCase();
        if(desc.isEmpty()){
            errorD=true;
            javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar una descripcion");
        }
        
        String cost=txtCosto.getText().trim();
        double cos = 0;
        if(cost.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar un valor para el costo");
            errorCos=true;}
        else
            cos=Double.parseDouble(cost);
        
        String porc=txtPorcGanancia.getText().trim();
        double por = 0;
        if(porc.isEmpty()){
            errorPor=true;
            javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar un valor para el porcentaje de ganancia");    }
        else
            por=Double.parseDouble(porc);
            
        boolean imp=opcImpSi.isSelected();
        if(!imp&&!opcImpNo.isSelected()){
            errorI=true;
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar su es importado o no");
        }
        
        if(!errorD&&!errorI&&!errorPor&&!errorCos){
            Articulo a=(Articulo)cmbListaArticulos.getSelectedItem();
            a.setDescripcion(desc);
            a.setCostoUnitario(cos);
            a.setPorcGanancia(por);
            a.setImportado(imp);
            limpiarPantalla();
            javax.swing.JOptionPane.showMessageDialog(null, "El articulo se modifico correctamente");

        } 
    }//GEN-LAST:event_btnConfirmarCambiosActionPerformed

    private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
        soloNumeros(evt, txtCosto);
    }//GEN-LAST:event_txtCostoKeyTyped

    private void txtPorcGananciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcGananciaKeyTyped
        soloNumeros(evt, txtPorcGanancia);
    }//GEN-LAST:event_txtPorcGananciaKeyTyped

    private void EliminarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarArticuloActionPerformed
        if(javax.swing.JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el articulo?")==0){
            Articulo art=(Articulo)cmbListaArticulos.getSelectedItem();
            comercio.removeArticulo(art);
            cmbListaArticulos.removeItem(art);
            limpiarPantalla();
        }
    }//GEN-LAST:event_EliminarArticuloActionPerformed

private VentanaPrincipal ventPrincipal;
private Comercio comercio;
LinkedList<Articulo> listArt;

        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarArticulo;
    private javax.swing.JButton btnConfirmarCambios;
    private javax.swing.ButtonGroup btnGroupImportado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Articulo> cmbListaArticulos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDatosDelArticulo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImportado;
    private javax.swing.JLabel lblPorcGanancia;
    private javax.swing.JLabel lblSeleccionarArticulo;
    private javax.swing.JLabel lblShowCodigo;
    private javax.swing.JLabel lblShowStockActual;
    private javax.swing.JLabel lblStockActual;
    private javax.swing.JRadioButton opcImpNo;
    private javax.swing.JRadioButton opcImpSi;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPorcGanancia;
    // End of variables declaration//GEN-END:variables
}
